spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      # show_sql: true
        format_sql: true
  h2:
    console:
      enabled: 'true'
      path: /h2
  redis:
    host: localhost
    port: '6379'

  servlet:
    ## MULTIPART (MultipartProperties)
    multipart:
      # Enable multipart uploads
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file:
  upload-dir: path
